### ISSUE TITLE
Evaluation protocol questions

### ISSUE THREAD

**Issue by mks0601** [patrikhuber/fg2018-competition#2]
Hi,

I'm trying to evaluate my algorithm on your dataset, but it seems the testing protocol is not clear for me.
In the dataset [website](http://pics.stir.ac.uk/ESRC/), there are [multiple 3D scans](http://pics.stir.ac.uk/ESRC/3d_images.htm). Which 3D scan should I use for the evaluation?

Also, in this repo, there are landmark groundtruths in `annotations` folder. However, Their names are not aligned with those of the images in your [test set](http://pics.stir.ac.uk/3Dfacedb/zips/Subset_2D_FG2018.zip). There are `M1000_N.lnd` and `M1000_NH.lnd`. What `H` stands for? Also, some `.lnd` file starts from capital `M`, but the others starts from small `m`. What does this difference mean? Finally, it seems there are missing `.lnd` files compared with images.

**Comment by patrikhuber** [comment]
Hi Gyeongsik,

> However, Their names are not aligned with those of the images in your test set.
> Finally, it seems there are missing .lnd files compared with images.

Hmm, it was more than two years ago when we put the scripts online. But what you describe sounds a bit weird.
The output of our algorithm looks something like this:

![image](https://user-images.githubusercontent.com/4967343/93709443-fc1fc380-fb35-11ea-8abc-fcc4dde8473e.png)

> There are M1000_N.lnd and M1000_NH.lnd. What H stands for?

I don't think this should matter. The meaning of the `H` might be documented in the original Stirling database description?

As you can see in my screenshot above, there are also no `N` or `NH` in our output filenames. Perhaps you are running your algorithm or the script on the wrong dataset / subset?

> Also, some .lnd file starts from capital M, but the others starts from small m. What does this difference mean?

I don't think this matters - it was probably a small typo when the annotations were originally created.


@fengzhenhua does anything catch your eyes?

**Comment by mks0601** [comment]
Thanks for the quick reply.
What I'm asking is this provided annotations [link](https://github.com/patrikhuber/fg2018-competition/tree/master/annotations/M_3D_N).
For example, there are `M1000_N.lnd`, `M1000_NH.lnd`, `m1000b_N.lnd`, and `m1000b_NH.lnd`. Which one should I use to evaluate image `M1000_*.jpg`?. Also, there is no `M1061*.lnd`, which makes hard to evauate `M1061_*.jpg`. Finally, `.lnd` files have no flag which indicates HQ or LQ. `M1000_N.lnd` means `M1000_*.jpg` from HQ or LQ?

**Comment by mks0601** [comment]
Also, could you answer this question included in my first issue?
Q. In the dataset website, there are multiple 3D scans. Which 3D scan should I use for the evaluation?

Thanks!

**Comment by patrikhuber** [comment]
Okay, I think the situation is getting clearer now.

> Finally, .lnd files have no flag which indicates HQ or LQ. M1000_N.lnd means M1000_*.jpg from HQ or LQ?

I think you have a slight misunderstanding. The `.lnd` files are 3D landmark annotations for the 3D scans - not for the 2D images. For example `M1000_N.lnd` are 3D landmarks for the scan `3D/M_3D_N.zip/M1000_N.obj` of the Stirling 3D face scans dataset. This is unrelated to the 2D LQ/HQ images.

> Also, there is no M1061*.lnd, which makes hard to evauate M1061_*.jpg

There is no `M1061*.lnd` because there is also no 3D scan (OBJ) for subject M1061 in the `M_3D_N.zip` Stirling 3D face scans dataset. It is probably our mistake that we included 2D images for this subject. I would say you can ignore the 2D images of subject M1061 in the evaluation.

> For example, there are M1000_N.lnd, M1000_NH.lnd, m1000b_N.lnd, and m1000b_NH.lnd. Which one should I use to evaluate image M1000_*.jpg?

I think you are correct, this might be a bit unfortunate that there are several 3D scans/annotations for subject M1000. 
However I think M1000 is more or less the only subject where this occurs - for all (most?) other subjects, there should only be one 3D scan / one set of 3D annotations. I think it is probably be if you use `M1000_N`.

> What H stands for?

It looks like `N` is the "default" and means the person is scanned with a head-cap. `NH` looks like it means the person is scanned without head-cap. For most people, there only exists a `N` scan, so for the very few people where there exist both, you can just use the `N` scan.

**Comment by patrikhuber** [comment]
@mks0601 Please also have a look at #3, which was reported to us last year but I just opened the issue now. It would be good if you could take this into account in your evaluation and compute both 3D-NME and 3D-RSME. Apologies that it is slightly messy.

**Comment by mks0601** [comment]
Unfortunately, there are more confusing annotations in [here](https://github.com/patrikhuber/fg2018-competition/tree/master/annotations/M_3D_N). Another example is `M1006_2_N.lnd` and `m1006_N.lnd`. Could you tell me how did you evaluate your algorithm using the provided [annotations](https://github.com/patrikhuber/fg2018-competition/tree/master/annotations)? As there is no HQ and LQ flag in the annotation and 3D scan, it is hard for me to evaluate for each image. For example, which 3D scan and 3D landmarks should I use to evaluate HQ/M1000_001.jpg ~ HQ/M1000_009.jpg and LQ/M1000_010.jpg  ~ LQ/M1000_015.jpg? It would be good if you can provide me triplets of (image path, 3D scan path, 3D landmark path) for the evaluation for all HQ and LQ images.

**Comment by patrikhuber** [comment]
I have now uploaded our script in #4 - this should show you how you can loop through your results, and pick the correct corresponding ground-truth 3D scan and `.lnd` files. The script should also answer your question question about the triplets.

I think you still have a misunderstanding about the HQ/LQ and 3D ground truth. The 2D LQ/HQ is independent of the 3D scan. The 3D scan is always the same. Only the 2D input image can be either LQ or HQ. I hope the above script clarifies this as well.
(For example, the ground-truth .lnd and .obj for both `HQ/M1000_0XX.jpg` and `LQ/M1000_0XX.jpg` is `M1000_N.lnd` and `3D/M_3D_N.zip/M1000_N.obj`.)

**Comment by mks0601** [comment]
OK I read it and it is more clear for me. It seems one 3D scan is used as GT for several images. For example, there are `HQ/F1001_01.jpg` ~ `HQ/F1001_08.jpg` and `LQ/F1001_08.jpg` ~ `LQ/F1001_017.jpg`. And maybe `F1001_N.obj` would be used as the GT 3D scan. However, the thing is that a woman in those images have different expressions, which can make my algorithm output different meshes. Evaluating images of the same subject and different expressions with a single 3D scan sounds weird. Did I understand correctly?

**Comment by patrikhuber** [comment]
> It seems one 3D scan is used as GT for several images. For example, there are HQ/F1001_01.jpg ~ HQ/F1001_08.jpg and LQ/F1001_08.jpg ~ LQ/F1001_017.jpg. And maybe F1001_N.obj would be used as the GT 3D scan.

Correct!

> However, the thing is that a woman in those images have different expressions, which can make my algorithm output different meshes. Evaluating images of the same subject and different expressions with a single 3D scan sounds weird. Did I understand correctly?

Correct. In this case, the task is not to reconstruct the exact 3D face shape from a particular image. The goal of the task is to reconstruct a subject's **neutral** 3D face (i.e. the identity) from the 2D images.

**Comment by mks0601** [comment]
Hmm.. sorry but still confusing to me :( So, the goal of this benchmark is to reconstruct only identity without expression and poses of neck, jaw, and eyes? Then for the evaluation, let's suppose I use a parametric face model such as [FLAME](https://flame.is.tue.mpg.de). For each image, my system predicts FLAME parameters including identity, expression and poses. In the evaluation stage, should I use estimated identity, neutral expression, zero poses to calculate errors for all images?

**Comment by patrikhuber** [comment]
> In the evaluation stage, should I use estimated identity, neutral expression, zero poses to calculate errors for all images?

Correct - but the pose won't matter as our evaluation script performs Procrustes alignment of the two meshes using the landmarks.

So you will still need an algorithm (like the FLAME fitting) that can estimate pose and expressions, because the 2D images contain them. And the benchmark then evaluates how well you were able to reconstruct the identity (neutral shape) of the person. So it will still ("indirectly") evaluate how good your expression and pose were fitted, because the better your pose and expressions have been estimated, the better presumably also your identity estimate will be.

**Comment by mks0601** [comment]
I see. I think the jaw and eye poses are local poses, so the Procrustes alignment cannot align them. Anyway, I understand. Thanks for detailed answers. By the way, maybe this benchmark is not suitable for model-free approaches, which directly predict mesh vertices without some pre-defined face model parameters?

**Comment by patrikhuber** [comment]
> I see. I think the jaw and eye poses are local poses, so the Procrustes alignment cannot align them.

Your output should be **one** `.obj` mesh of the whole face. This can then be aligned with the groundtruth scan. I'm sure FLAME offers some way to "merge" the jaw and eyes into one consistent face mesh?

> By the way, maybe this benchmark is not suitable for model-free approaches, which directly predict mesh vertices without some pre-defined face model parameters?

Model parameters are not needed. The benchmark works with any algorithm, as long as the output is one mesh (i.e. set of vertices). If the output meshes don't have a consistent topology, then you could just use another strategy instead of Procrustes to do the initial alignment, and then measure the distance between the two meshes.

**Comment by patrikhuber** [comment]
Ah, I think I see what you mean now. Yes, the algorithm needs to be able to estimate/output a neutral face shape, or have a way to separate the identity from expressions. So an approach that just predicts a mesh with expressions, but no way of separating them, would not be able to solve the task of this benchmark.

**Comment by mks0601** [comment]
Perfect. Thanks!

**Comment by patrikhuber** [comment]
You're welcome, glad I could help!

I would be very interested to hear what happens with your evaluation, if you would like to report back.

Best wishes,
Patrik
